<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit93cd361507d0cdbf8f1b49ad9e1273d8
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Buki\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Buki\\' => 
        array (
            0 => __DIR__ . '/..' . '/izniburak/pdox/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit93cd361507d0cdbf8f1b49ad9e1273d8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit93cd361507d0cdbf8f1b49ad9e1273d8::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
